---
grails:
    profile: rest-api
    codegen:
        defaultPackage: grails_server
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    gorm:
        failOnError: true
    cors:
        enabled: true
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

environments:
    development:
        dataSource:
            pooled: true
            dbCreate: update
            url: jdbc:mysql://localhost:3306/tester
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: root
            password: loot1234
            properties:
              jmxEnabled: true
              initialSize: 5
              maxActive: 50
              minIdle: 5
              maxIdle: 25
              maxWait: 10000
              maxAge: 10 * 60000
              timeBetweenEvictionRunsMillis: 5000
              minEvictableIdleTimeMillis: 60000
              validationQuery: SELECT 1
              validationQueryTimeout: 3
              validationInterval: 15000
              testOnBorrow: true
              testWhileIdle: true
              testOnReturn: false
              jdbcInterceptors: ConnectionState;StatementCache(max=200)
              defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            pooled: true
            dbCreate: update
            url: jdbc:mysql://localhost:3306/tester
            driverClassName: com.mysql.jdbc.Driver
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            username: root
            password: loot1234
            properties:
              jmxEnabled: true
              initialSize: 5
              maxActive: 50
              minIdle: 5
              maxIdle: 25
              maxWait: 10000
              maxAge: 10 * 60000
              timeBetweenEvictionRunsMillis: 5000
              minEvictableIdleTimeMillis: 60000
              validationQuery: SELECT 1
              validationQueryTimeout: 3
              validationInterval: 15000
              testOnBorrow: true
              testWhileIdle: true
              testOnReturn: false
              jdbcInterceptors: ConnectionState;StatementCache(max=200)
              defaultTransactionIsolation: java.sql.Connection.TRANSACTION_READ_COMMITTED
server:
    port: 9090